---
- hosts: localhost
  user: cjp
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew
    - hnakamur.oh-my-zsh
    - geerlingguy.dotfiles
    
  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml

